/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminSiteSettingsRouteImport } from './routes/_admin.site-settings'
import { Route as AdminProductsRouteImport } from './routes/_admin.products'
import { Route as AdminAuditLogsRouteImport } from './routes/_admin.audit-logs'
import { Route as AdminProductsNewRouteImport } from './routes/_admin.products.new'
import { Route as AdminProductsIdEditRouteImport } from './routes/_admin.products.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/products': typeof AdminProductsRouteWithChildren
  '/site-settings': typeof AdminSiteSettingsRoute
  '/products/new': typeof AdminProductsNewRoute
  '/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/products': typeof AdminProductsRouteWithChildren
  '/site-settings': typeof AdminSiteSettingsRoute
  '/': typeof AdminIndexRoute
  '/products/new': typeof AdminProductsNewRoute
  '/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/products': typeof AdminProductsRouteWithChildren
  '/_admin/site-settings': typeof AdminSiteSettingsRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/products/new': typeof AdminProductsNewRoute
  '/_admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/products'
    | '/site-settings'
    | '/products/new'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit-logs'
    | '/products'
    | '/site-settings'
    | '/'
    | '/products/new'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/audit-logs'
    | '/_admin/products'
    | '/_admin/site-settings'
    | '/_admin/'
    | '/_admin/products/new'
    | '/_admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/site-settings': {
      id: '/_admin/site-settings'
      path: '/site-settings'
      fullPath: '/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-logs': {
      id: '/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products/new': {
      id: '/_admin/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/_admin/products/$id/edit': {
      id: '/_admin/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
